package com.me.recyclerviewpreview

import com.google.gson.Gson
import com.google.gson.reflect.TypeToken

fun getData(): List<Story> {
    val gson = Gson()
    val type = object : TypeToken<List<Story>>() {}.type
    return gson.fromJson(DATA, type)
}

private const val DATA = """
    [
        {
            "nid": "128491",
            "title": "S'pore faces talent crunch as tech giants scale up ",
            "title_url": "/singapore/spore-faces-talent-crunch-tech-giants-scale-128491",
            "absolute_url": "https://mediacorptdystg.prod.acquia-sites.com/singapore/spore-faces-talent-crunch-tech-giants-scale-128491",
            "description": "<p>SINGAPORE — At least three recruiters approach Singapore-based software engineer Xiao Yuguang every day with job offers.<br />\n </p>\n",
            "release_date": "2021-02-22T11:17:00",
            "image_url": "https://res.cloudinary.com/onecms-dev/image/upload/s--jXx7C6Lq--/f_auto%2Cq_auto/v1/mediacorp/one-cms/images/2021-01/20200115_am_data_br.jpg?itok=o1-2dsDG",
            "video": {
                "video_id": "6226583833001",
                "duration": "00:30",
                "account_id": "6100381023001"
            },
            "category": "Singapore",
            "changed_date": "2021-03-01T20:27:15",
            "flag": "live",
            "liveblog_source": "",
            "uuid": "26ae3c0a-8a88-4419-b5be-093aa64f762c",
            "author": "Louisa Tang"
        },
        {
            "nid": "166326",
            "title": "Man to be charged with money laundering offences linked to S${'$'}10.2 million Covid-19 scam",
            "title_url": "/singapore/man-be-charged-money-laundering-offences-linked-s102-million-covid-19-scam-166326",
            "absolute_url": "https://mediacorptdystg.prod.acquia-sites.com/singapore/man-be-charged-money-laundering-offences-linked-s102-million-covid-19-scam-166326",
            "description": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\n",
            "release_date": "2021-02-23T17:06:00",
            "image_url": "https://res.cloudinary.com/onecms-dev/image/upload/s--VyWRMVAf--/f_auto%2Cq_auto/v1/onecms/omnystudio/image_1683.jpg?itok=CWoYYS12",
            "video": [],
            "image": null,
            "category": "Singapore",
            "changed_date": "2021-03-04T13:35:28",
            "flag": null,
            "liveblog_source": "",
            "uuid": "00534244-4e6c-409f-907e-fcc400292988",
            "author": null
        },
        {
            "nid": "128486",
            "title": "President Halimah Yacob receives first dose of Pfizer-BioNTech Covid-19 vaccine ",
            "title_url": "/world/president-halimah-yacob-receives-first-dose-pfizer-biontech-covid-19-vaccine-128486",
            "absolute_url": "https://mediacorptdystg.prod.acquia-sites.com/world/president-halimah-yacob-receives-first-dose-pfizer-biontech-covid-19-vaccine-128486",
            "description": "<p>SINGAPORE — President Halimah Yacob was given the Covid-19 vaccine on Wednesday (Jan 27) afternoon at the Outram Polyclinic.<br />\n </p>\n",
            "release_date": "2021-01-28T04:29:00",
            "image_url": "https://res.cloudinary.com/onecms-dev/image/upload/s--aUs38LtN--/f_auto%2Cq_auto/v1/mediacorp/one-cms/images/2021-01/sample-image-6.jpg?itok=lSkjQm-e",
            "video": [],
            "image": null,
            "category": "World",
            "changed_date": "2021-01-28T14:19:09",
            "flag": null,
            "liveblog_source": "",
            "uuid": "6f4a850b-c373-481e-bdbd-9621a59c7f32",
            "author": "NAVENE ELANGOVAN"
        },
        {
            "nid": "128481",
            "title": "25 new imported Covid-19 cases in Singapore, 16 are foreign domestic workers. ",
            "title_url": "/singapore/25-new-imported-covid-19-cases-singapore-16-are-foreign-domestic-workers-128481",
            "absolute_url": "https://mediacorptdystg.prod.acquia-sites.com/singapore/25-new-imported-covid-19-cases-singapore-16-are-foreign-domestic-workers-128481",
            "description": null,
            "release_date": "2021-02-28T04:27:00",
            "image_url": "https://res.cloudinary.com/onecms-dev/image/upload/s--YbiQrs-u--/f_auto%2Cq_auto/v1/mediacorp/one-cms/images/2021-03/travellers-wait-at-a-departure-hall.jpg?itok=bbSSo282",
            "video": [],
            "image": null,
            "category": "Singapore",
            "changed_date": "2021-03-03T22:56:33",
            "flag": null,
            "liveblog_source": "",
            "uuid": "c5915622-f84a-42fc-9889-2cdb64318f65",
            "author": "Kamala Harris"
        },
        {
            "nid": "128476",
            "title": "16-year-old S’porean who made ‘detailed plans’ to attack 2 mosques in Woodlands detained under ISA ",
            "title_url": "/singapore/16-year-old-sporean-who-made-detailed-plans-attack-2-mosques-woodlands-detained-under-isa",
            "absolute_url": "https://mediacorptdystg.prod.acquia-sites.com/singapore/16-year-old-sporean-who-made-detailed-plans-attack-2-mosques-woodlands-detained-under-isa",
            "description": "<p>SINGAPORE — A 16-year-old Singaporean boy was detained under the Internal Security Act (ISA) in December last year after he was found to have made “detailed plans” and preparations to conduct terror attacks against Muslims at two mosques here with a machete!<br />\n </p>\n",
            "release_date": "2021-01-28T04:26:23",
            "image_url": "https://res.cloudinary.com/onecms-dev/image/upload/s--u7KwCL4W--/f_auto%2Cq_auto/v1/mediacorp/one-cms/images/2021-01/sample-image-hp.jpg?itok=VneBRKnD",
            "video": [],
            "image": null,
            "category": "Singapore",
            "changed_date": "2021-01-28T12:26:23",
            "flag": null,
            "liveblog_source": "",
            "uuid": "cb18b539-4036-4467-b1ba-e8286a0edf3c",
            "author": null
        },
        {
            "nid": "27416",
            "title": "Singapore’s labour market could bottom out by end-2020, but uneven recovery may widen income gap: Analysts",
            "title_url": "/heng-swee-keat/singapores-labour-market-could-bottom-out-end-2020-uneven-recovery-may-widen-income",
            "absolute_url": "https://mediacorptdystg.prod.acquia-sites.com/heng-swee-keat/singapores-labour-market-could-bottom-out-end-2020-uneven-recovery-may-widen-income",
            "description": "<div style=\"display: none;\"> </div>\n\n<p> </p>\n",
            "release_date": "2020-11-14T08:34:00",
            "image_url": "https://res.cloudinary.com/onecms-dev/image/upload/s--KActETXC--/f_auto%2Cq_auto/v1/mediacorp/one-cms/images/2021-02/file_example_JPG_1MB_0.jpg?itok=e3rwHhd0",
            "video": [],
            "image": null,
            "category": "Eat & Drink",
            "changed_date": "2021-01-27T16:29:55",
            "flag": null,
            "liveblog_source": "",
            "uuid": "d92214e1-b51e-4c5c-ac75-d2f25d965e1b",
            "author": null
        },
        {
            "nid": "32306",
            "title": "Mutated COVID-19 from mink in Denmark most likely extinct, health ministry says",
            "title_url": "/covid-19/mutated-covid-19-mink-denmark-most-likely-extinct-health-ministry-says-32306",
            "absolute_url": "https://mediacorptdystg.prod.acquia-sites.com/covid-19/mutated-covid-19-mink-denmark-most-likely-extinct-health-ministry-says-32306",
            "description": null,
            "release_date": "2020-11-19T15:00:00",
            "image_url": "https://res.cloudinary.com/onecms-dev/image/upload/s--KActETXC--/f_auto%2Cq_auto/v1/mediacorp/one-cms/images/2021-02/file_example_JPG_1MB_0.jpg?itok=e3rwHhd0",
            "video": [],
            "image": null,
            "category": "Lifestyle",
            "changed_date": "2021-01-25T21:19:36",
            "flag": null,
            "liveblog_source": "",
            "uuid": "a5566566-dc90-49d0-8315-ae15c96a701d",
            "author": null
        },
        {
            "nid": "29556",
            "title": "US Postal Service says 1,700 ballots found in Pennsylvania facilities",
            "title_url": "/asia/us-postal-service-says-1700-ballots-found-pennsylvania-facilities-29556",
            "absolute_url": "https://mediacorptdystg.prod.acquia-sites.com/asia/us-postal-service-says-1700-ballots-found-pennsylvania-facilities-29556",
            "description": null,
            "release_date": "2020-11-06T15:16:00",
            "image_url": "https://res.cloudinary.com/onecms-dev/image/upload/s--KActETXC--/f_auto%2Cq_auto/v1/mediacorp/one-cms/images/2021-02/file_example_JPG_1MB_0.jpg?itok=e3rwHhd0",
            "video": [],
            "image": null,
            "category": "Big Read",
            "changed_date": "2021-01-25T20:46:01",
            "flag": null,
            "liveblog_source": "",
            "uuid": "625ee1cc-d68a-40e1-9e61-6893f21818a3",
            "author": "Priyanka Sahni"
        },
        {
            "nid": "27541",
            "title": "COVID-19: Singapore, Hong Kong reach in-principle agreement to establish bilateral air travel bubble",
            "title_url": "/north-korea/covid-19-singapore-hong-kong-reach-principle-agreement-establish-bilateral-air-travel",
            "absolute_url": "https://mediacorptdystg.prod.acquia-sites.com/north-korea/covid-19-singapore-hong-kong-reach-principle-agreement-establish-bilateral-air-travel",
            "description": null,
            "release_date": "2021-01-19T08:50:14",
            "image_url": "https://res.cloudinary.com/onecms-dev/image/upload/s--KActETXC--/f_auto%2Cq_auto/v1/mediacorp/one-cms/images/2021-02/file_example_JPG_1MB_0.jpg?itok=e3rwHhd0",
            "video": [],
            "image": null,
            "category": "North Korea",
            "changed_date": "2021-01-19T16:50:14",
            "flag": null,
            "liveblog_source": "",
            "uuid": "b9765e14-c3ed-4cea-be1b-a811ba392ca0",
            "author": null
        },
        {
            "nid": "27126",
            "title": "Now open: Chef Andrew Walsh’s highly anticipated seafood restaurant Catfish",
            "title_url": "/now-open-chef-andrew-walshs-highly-anticipated-seafood-restaurant-catfish-27126",
            "absolute_url": "https://mediacorptdystg.prod.acquia-sites.com/now-open-chef-andrew-walshs-highly-anticipated-seafood-restaurant-catfish-27126",
            "description": "<p>The Irish chef of acclaimed restaurant Cure has created his vision of the sexy, contemporary seafood joint that he believes this city needs.</p>\n\n<p> </p>\n",
            "release_date": "2020-10-05T17:33:23",
            "image_url": "https://res.cloudinary.com/onecms-dev/image/upload/s--KActETXC--/f_auto%2Cq_auto/v1/mediacorp/one-cms/images/2021-02/file_example_JPG_1MB_0.jpg?itok=e3rwHhd0",
            "video": [],
            "image": null,
            "category": null,
            "changed_date": "2021-01-14T01:17:12",
            "flag": null,
            "liveblog_source": "",
            "uuid": "3b67cd52-4d3d-4ce1-a487-a562b296c3b3",
            "author": null
        },
        {
            "nid": "29581",
            "title": "17 US states report record increases in COVID-19 cases amid close election",
            "title_url": "/asia/17-us-states-report-record-increases-covid-19-cases-amid-close-election-29581",
            "absolute_url": "https://mediacorptdystg.prod.acquia-sites.com/asia/17-us-states-report-record-increases-covid-19-cases-amid-close-election-29581",
            "description": null,
            "release_date": "2020-11-06T15:19:00",
            "image_url": "https://res.cloudinary.com/onecms-dev/image/upload/s--KActETXC--/f_auto%2Cq_auto/v1/mediacorp/one-cms/images/2021-02/file_example_JPG_1MB_0.jpg?itok=e3rwHhd0",
            "video": [],
            "image": null,
            "category": "Big Read",
            "changed_date": "2021-01-14T01:17:12",
            "flag": null,
            "liveblog_source": "",
            "uuid": "4710a448-67a3-4596-8d47-613e58ec7fdd",
            "author": null
        },
        {
            "nid": "168766",
            "title": "From condo to airline tickets, discounts galore as firms jump on Singles Day bandwagon",
            "title_url": "/singapore/condo-airline-tickets-discounts-galore-firms-jump-singles-day-bandwagon-168766",
            "absolute_url": "https://mediacorptdystg.prod.acquia-sites.com/singapore/condo-airline-tickets-discounts-galore-firms-jump-singles-day-bandwagon-168766",
            "description": null,
            "release_date": "2021-03-04T13:38:00",
            "image_url": "https://res.cloudinary.com/onecms-dev/image/upload/s--jeShHufc--/f_auto%2Cq_auto/v1/mediacorp/one-cms/images/2021-01/sample-world-image-1.jpg?itok=qbyRVYCB",
            "video": [],
            "image": null,
            "category": "Singapore",
            "changed_date": "2021-03-04T22:16:04",
            "flag": "exclusive",
            "liveblog_source": "",
            "uuid": "0ff63aef-f0b7-44fc-9447-b9ec93c437b0",
            "author": "Louisa Tang"
        },
        {
            "nid": "167721",
            "title": "Test OC-5639",
            "title_url": "/brand-spotlight/test-oc-5639-167721",
            "absolute_url": "https://mediacorptdystg.prod.acquia-sites.com/brand-spotlight/test-oc-5639-167721",
            "description": null,
            "release_date": "2021-03-02T07:41:37",
            "image_url": "",
            "video": [],
            "image": null,
            "category": "Brand Spotlight",
            "changed_date": "2021-03-02T15:41:36",
            "flag": null,
            "liveblog_source": "",
            "uuid": "d8e4bafc-c259-4a11-84d6-5171931de2af",
            "author": null
        },
        {
            "nid": "167366",
            "title": "a",
            "title_url": "/brand-spotlight/a-167366",
            "absolute_url": "https://mediacorptdystg.prod.acquia-sites.com/brand-spotlight/a-167366",
            "description": null,
            "release_date": "2021-02-26T10:02:42",
            "image_url": "",
            "video": [],
            "image": null,
            "category": "Brand Spotlight",
            "changed_date": "2021-02-26T18:02:42",
            "flag": null,
            "liveblog_source": "",
            "uuid": "5f359713-91f4-41c7-ba31-993715cccdb1",
            "author": null
        },
        {
            "nid": "167231",
            "title": "Testing for embed ",
            "title_url": "/singapore/testing-embed-167231",
            "absolute_url": "https://mediacorptdystg.prod.acquia-sites.com/singapore/testing-embed-167231",
            "description": "<p>This is the abstract</p>\n",
            "release_date": "2021-02-26T02:19:00",
            "image_url": "",
            "video": [],
            "image": null,
            "category": "Singapore",
            "changed_date": "2021-02-26T17:13:17",
            "flag": null,
            "liveblog_source": "",
            "uuid": "9d6ba7c4-23bd-4a86-a01b-bfadd6b4272f",
            "author": null
        },
        {
            "nid": "167076",
            "title": "Demo Article Page",
            "title_url": "/lifestyle/demo-article-page-167076",
            "absolute_url": "https://mediacorptdystg.prod.acquia-sites.com/lifestyle/demo-article-page-167076",
            "description": "<h2>What is Lorem Ipsum?</h2>\n\n<p><strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>\n",
            "release_date": "2021-02-25T09:26:00",
            "image_url": "https://res.cloudinary.com/onecms-dev/image/upload/s--1tV0QPMx--/f_auto%2Cq_auto/v1/onecms/omnystudio/image_2030.jpg?itok=Iln1uCsY",
            "video": [],
            "image": null,
            "category": "Lifestyle",
            "changed_date": "2021-02-25T17:43:46",
            "flag": null,
            "liveblog_source": "",
            "uuid": "98ef4814-cec9-4cb1-aac4-303ffbc33cd5",
            "author": null
        },
        {
            "nid": "166711",
            "title": "this is news",
            "title_url": "/video/news-166711",
            "absolute_url": "https://mediacorptdystg.prod.acquia-sites.com/video/news-166711",
            "description": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\n",
            "release_date": "2021-02-24T14:10:00",
            "image_url": "https://res.cloudinary.com/onecms-dev/image/upload/s--BpDG7Ksv--/f_auto%2Cq_auto/v1/mediacorp/one-cms/images/2021-02/image_48.jpg?itok=j5xiaQS_",
            "video": {
                "video_id": "6225150316001",
                "duration": "00:10",
                "account_id": "6100381023001"
            },
            "category": "Brand Spotlight",
            "changed_date": "2021-02-24T22:55:06",
            "flag": null,
            "liveblog_source": "",
            "uuid": "2e52ed53-3cb6-4742-9164-4be99624042c",
            "author": null,
            "duration": "10"
        },
        {
            "nid": "166706",
            "title": "sdsfs",
            "title_url": "/commentary/sdsfs-166706",
            "absolute_url": "https://mediacorptdystg.prod.acquia-sites.com/commentary/sdsfs-166706",
            "description": "<p>Text, + Image, + Gallery…Text, + Image, + Gallery…Text, + Image, + Gallery…Text, + Image, + Gallery…Text, + Image, + Gallery…</p>\n",
            "release_date": "2021-02-24T12:38:00",
            "image_url": "",
            "video": [],
            "image": null,
            "category": "Commentary",
            "changed_date": "2021-02-24T20:45:29",
            "flag": null,
            "liveblog_source": "",
            "uuid": "67eae53b-72b6-4ba9-b27d-a8c4ef4cb321",
            "author": null
        }
    ]
"""